### ISSUE TITLE
Missing TargetPrescriptionDose when DoseReferenceStructureType exists results in crash

### ISSUE THREAD

**Issue by sjswerdloff** [didymo/OnkoDICOM#15]
When a plan has the dose reference sequence, that sequence must have a Dose Reference StructureType (type 1), but it does not have to have a Target Prescription Dose (type 3).
For plans that have the Dose Reference Sequence but do not have a Target Prescription Dose, the application crashes when trying to access the value

**Comment by celeron533** [comment]
When `TargetPrescriptionDose` does not exist in list, it still throw the exception. Could solve this by checking the key before use:

```
            if ('DoseReferenceSequence' in self.dataset['rtplan'] and
                'DoseReferenceStructureType' in self.dataset['rtplan'].DoseReferenceSequence[0] and
                self.dataset['rtplan'].DoseReferenceSequence[0].DoseReferenceStructureType and
                'TargetPrescriptionDose' in self.dataset['rtplan'].DoseReferenceSequence[0] and
                self.dataset['rtplan'].DoseReferenceSequence[0].TargetPrescriptionDose):
```
