### ISSUE TITLE
Consider indicating that this is derived work or a fork of dicompyler

### ISSUE THREAD

**Issue by bastula** [didymo/OnkoDICOM#18]
Great work on this project! I am glad to see that it is taking wings and love to see the direction it ends up.

However, as this originally began as a fork of `dicompyler` (and continues to use the `dicompyler-core` library internally as one of it's dependencies), it would be a kind gesture to indicate that either on this repository or on your homepage. A lot of work went into that project which I am sure has been an inspiration for this one.

Cheers!

**Comment by oismaster** [comment]
@bastula you are entirely correct and no disrespect is intended. I have been writing up the description and adding projects as a way of centralising the plans. I haven't finished editing but I'll make those corrections immediately.

I applaud you for the work you did on DICOMpyler and its reputation is entirely appropriate and well earned.

**Comment by oismaster** [comment]
@bastula can you review the edited version, I am not a developer so I am unsure if I have been accurate. If I'm not, please correct me.

**Comment by bastula** [comment]
@oismaster To which description are you referring to? I am more than happy to review. Is there a document or a fork or specific commit you are referring to?

Thank you for the kind words.

**Comment by bastula** [comment]
Sorry, I see that you were referencing the Project tab in this Github repo. Yes the narrative is fine, and hopefully this makes it to the project readme.

Thank you!

**Comment by oismaster** [comment]
Ok, I'll look at that. Ashley was happy with my plans for attribution but
wants to in some specific place that I will discover soon.

I talked with Simon Biggs yesterday and he had a lot of useful input too.

A

**Comment by SimonBiggs** [comment]
Hi @oismaster :),

My tag is @SimonBiggs, so feel free to ping me also :)

**Comment by bastula** [comment]
@didymo @oismaster The readme, project description and website are still mostly verbatim copied from dicompyler. Please consider proper attribution to the original project.

**Comment by didymo** [comment]
this issue is being reopened. This is matter is part of a wider range of tasks.

**Comment by didymo** [comment]
dicompyler-core is an essential dependency of the project, this was not attributed, it always should have been attributed, it is now, a rewrite of many areas providing attribution is part of several items.
