### ISSUE TITLE
Crashes while Save as Anonymous

### ISSUE THREAD

**Issue by kundan1974** [didymo/OnkoDICOM#256]
I am only using dicom image with no clinical data. After calculating pyradiomics when i try to use "save as anonymous" program crashes with these outputs in the console/

<class 'NameError'> name 'FEATURE_TOGGLE_PSEUDONYMISE' is not defined <traceback object at 0x7fc17ba47e00>
Traceback (most recent call last):
  File "/home/ant/projects/pycharm_projects/OnkoDICOM/src/Controller/ActionHandler.py", line 325, in anonymization_handler
    hashed_path = self.__main_page.call_class.run_anonymization(
  File "/home/ant/projects/pycharm_projects/OnkoDICOM/src/Controller/MainPageController.py", line 400, in run_anonymization
    if not FEATURE_TOGGLE_PSEUDONYMISE:
NameError: name 'FEATURE_TOGGLE_PSEUDONYMISE' is not defined

**Comment by sjswerdloff** [comment]
In src/Controller/MainPageController.py: missing declaration if successful import
```
try:
    from src.Model.Anon import anonymize
    FEATURE_TOGGLE_PSEUDONYMISE = True # need to declare if successful
except ImportError as ePymedphysImportFailed:
    FEATURE_TOGGLE_PSEUDONYMISE = False
    logging.error(ePymedphysImportFailed)

```

**Comment by sjswerdloff** [comment]
> I have calculated the pyradiomics features, and then when I try to anonymise, there is a new error RecursionError: maximum recursion depth exceeded Also in my original folder it does create a Pyradiomics-SR.dcm file and a CSV folder. But CSV folder is empty. So how to export pyradiomics features into a CSV file
> […](#)

I have created two new issues for the two separate items you mentioned.
Please look at #259 and reply there so we can investigate.
