### ISSUE TITLE
[Dependency management] Move to Poetry and minimize the requirements.txt

### ISSUE THREAD

**Issue by celeron533** [didymo/OnkoDICOM#273]
Hi All,
I noticed that project is using Poetry as the package manager. Should the project to remove the redundant items in requirements.txt, or even delete this file in the future?

**Comment by celeron533** [comment]
Currently I am working on move everything to Poetry and have a working prototype right now.

**Comment by didymo** [comment]
thanks

**Comment by celeron533** [comment]
PR #275 
Next step: update the readme.md and lint some of the code.
