### ISSUE TITLE
Incorrect instructions in README.md

### ISSUE THREAD

**Issue by LWMcClymont** [didymo/OnkoDICOM#94]
Incorrect directory separator in README.md file, line 51.

`venv/Scripts/activate.bat`

Should be:  `venv\Scripts\activate.bat`

The correct directory separator for Windows is `\`

Currently, if the command were to be executed, the following error would appear:

`"'venv' is not recognized as an internal or external command,
operable program or batch file."`

**Comment by Fincap** [comment]
The [installation instructions provided in the wiki ](https://github.com/didymo/OnkoDICOM/wiki/Installation-Instructions) are more up-to-date and accurate than those provided in the readme. I will make a pull request to update the readme to reflect this change.
