### ISSUE TITLE
The wiki instructions for Windows has a typo (duplicate 'git clone' on the command line) and refers to a fork rather than the official repo.

### ISSUE THREAD

**Issue by sjswerdloff** [didymo/OnkoDICOM#96]
The wiki instructions for Windows has a typo (duplicate 'git clone' on the command line) and refers to a fork rather than the official repo. 

git clone git clone https://github.com/Fincap/OnkoDICOM.git
cd OnkoDICOM

_Originally posted by @sjswerdloff in https://github.com/didymo/OnkoDICOM/pull/95#issuecomment-841785621_

**Comment by Fincap** [comment]
Thanks for spotting that, has been fixed now.
